[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework =

lib_ignore = FrameworkCMSISDevice

build_src_filter =
    +<../main.c>
    +<../syscalls.c>
    +<../autosar/Com/Com.c>
    +<../../autosar/PduR/PduR.c>
    +<../../autosar/Canif/CanIf.c>
    +<../../autosar/Can/Can.c>
    +<../config/Com_Cfg.c>
    +<../../config/CanIf_Cfg.c>
    +<../../config/PduR_Cfg.c>
    +<../../config/Can_Cfg.c>
    +<../../spl/src/stm32f10x_rcc.c>
    +<../../spl/src/stm32f10x_gpio.c>
    +<../../spl/src/stm32f10x_can.c>
    +<../../spl/src/misc.c>
    +<../../spl/src/system_stm32f10x.c>

build_flags =
    -DSTM32F10X_MD
    -DPDUR_USE_COM
    -DUSE_STDPERIPH_DRIVER
    -IE:/AUTOSAR_Tai_Lieu/Student_ECU/autosar/include
    -IE:/AUTOSAR_Tai_Lieu/Student_ECU/autosar/Can
    -IE:/AUTOSAR_Tai_Lieu/Student_ECU/autosar/Canif
    -IE:/AUTOSAR_Tai_Lieu/Student_ECU/autosar/PduR
    -IE:/AUTOSAR_Tai_Lieu/Student_ECU/Com_ECU/autosar/Com
    -IE:/AUTOSAR_Tai_Lieu/Student_ECU/config
    -IE:/AUTOSAR_Tai_Lieu/Student_ECU/Com_ECU/config
    -IE:/AUTOSAR_Tai_Lieu/Student_ECU/spl/inc
    -IE:/AUTOSAR_Tai_Lieu/Student_ECU/bsp/cmsis

