/* Generated by HALA SIM. Regenerate from the project context menu. */
typedef unsigned int uint32_t;
extern int main(void);
extern uint32_t _sidata, _sdata, _edata, _sbss, _ebss;
__attribute__((weak)) void SystemInit(void) {}
void Default_Handler(void) { for (;;) __asm volatile("nop"); }
void Reset_Handler(void) {
  uint32_t *src = &_sidata;
  for (uint32_t *dst = &_sdata; dst < &_edata;) *dst++ = *src++;
  for (uint32_t *dst = &_sbss; dst < &_ebss;) *dst++ = 0;
  SystemInit();
  (void)main();
  for (;;) __asm volatile("nop");
}
__attribute__((used, section(".isr_vector")))
void (* const vectors[])(void) = {
  (void (*)(void))0x20005000u, Reset_Handler,
  Default_Handler, Default_Handler, Default_Handler, Default_Handler,
  Default_Handler, Default_Handler, Default_Handler, Default_Handler,
  Default_Handler, Default_Handler, Default_Handler, Default_Handler,
  Default_Handler, Default_Handler
};
